- hosts: localhost
  connection: local
  become: true
  
  tasks: 
  - name: Install htop
    apt:
      name: htop
  - name: Install vim
    apt:
      name: vim
  - name: Install tmux
    apt:
      name: tmux
